name: MoreOres
version: 1.2.0
author: JohZant
main: com.arch.moreores.MoreOres
website: www.archetype-mc.com

commands:
   moreores:
      description: MoreOres Base Command

permissions:
   moreores.*:
     description: Gives access to all MoreOres commands
     default: op
     children:
       moreores.admin: true
   moreores.admin:
     description: Gives access to administrative command subsection
     default: op
     children:
       moreores.admin.reload: true
       moreores.admin.toggle: true